package com.borrowbox.entity;

public enum NotificationType {
    REQUEST_RECEIVED,
    REQUEST_ACCEPTED,
    REQUEST_REJECTED,
    REQUEST_CANCELLED,
    TRANSACTION_CREATED,
    PICKUP_REMINDER,
    PICKUP_CONFIRMED,
    RETURN_REMINDER,
    RETURN_PENDING,
    RETURN_CONFIRMED,
    OVERDUE,
    DISPUTE_OPENED,
    DISPUTE_UPDATED,
    RATING_RECEIVED,
    CHAT_MESSAGE,
    ITEM_AVAILABLE
}
